"""empty message

Revision ID: 619068c772e7
Revises: 7cf7a8299ee5
Create Date: 2024-11-11 10:26:03.761742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619068c772e7'
down_revision = '7cf7a8299ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
